product_category_relations:
  spy/shop-by-solution/security-systems/home-security:
    products:
      - TVEZ32
      - TVIPH2G
      - TVEZ34
      - TVI7T4H
      - DVRNNPH
      - DVRNNMB
  spy/shop-by-solution/security-systems/business-security:
    products:
      - PKIP74
      - PKIPANPR2
      - PKIP78
      - PKIP34
      - PKIP38
      - PK4K32
      - PK4K74
      - PK4K34
      - DVRNNPH
      - DVRNNMB
  spy/shop-by-solution/security-systems/vehicle-security:
    products:
      - SPYZ15
      - SPYZ16
      - GNETGPS
      - SPYDCAR
      - VPIP82
  spy/shop-by-solution/security-systems/farm-security:
    products:
      - WLIP230B
      - WLPTZIP2B
      - WLPTZHKD
      - TVI3T4WL
      - WL3ADIG24
      - PKE244WL
      - WLEZADIG24
      - DW34QUALR
      - DW3E4B1TB1
  spy/shop-by-solution/covert-recording/home:
    products:
      - PH701
      - GTTV505MBGB
      - GTTV505PHGB
      - PHPEEPGB
      - SPYDFOBW
      - SPYDUSBW
      - SPYDHPW
      - HCAME1B
      - SPYZ15
      - SPYZ16
      - SPYDV90
      - SPYDALC
      - DVRNNPH
      - DVRNNMB
  spy/shop-by-solution/covert-recording/office:
    products:
      - GT4TV2SMKGB
      - GTIP2SMKWF
      - GTIP2PIRWF
      - NNTV205MBGB
      - NNTV205PHGB
      - SPYDCUPW
      - SPYZ32IR
      - SPYZ62WF
      - HKIP205PH-LS
      - FSIP207PTZ
      - SPYDPKDVR1
      - SPYDCAMBW
      - DVRNNPH
      - DVRNNMB
  spy/shop-by-solution/covert-recording/battery:
    products:
      - SPYZ15
      - SPYZ16
      - SPYZ18
      - SPYZ32IR
      - SPYZ62WF
      - HCAME1B
      - SPYDCAR
      - SPYDV90
      - SPYDCUPW
      - SPYDFOBW
      - SPYDPKDVR1
      - SPYDALC
      - SPYDCAMBW
  spy/shop-by-solution/covert-recording/vehicle:
    products:
      - SPYZ15
      - SPYZ16
      - SPYDCAR
  spy/shop-by-solution/wildlife/bird-box-cameras:
    products:
      - NC701G
      - NCIP9WF
      - CMOSNC720M
      - NCIP220M
      - NCIP9WFBB
      - CMOSNC720MBB
      - NC701GBB
      - NCF15EA20M
      - 2NCIP2
      - NCIP2
  spy/shop-by-solution/wildlife/farming:
    products:
      - WLIP230B
      - WLPTZIP2B
      - WLPTZHKD
      - TVI3T4WL
      - WL3ADIG24
      - PKE244WL
      - WLEZADIG24
      - DW34QUALR
      - DW3E4B1TB1
  spy/shop-by-solution/wildlife/trail-cameras:
    products:
      - HCAME1B
      - HCAME1BOX
  spy/shop-by-solution/wildlife/garden-wildlife:
    products:
      - HCAME1B
      - EZ4SD20B20M
  spy/our-full-range/spy-cameras/pinhole-cameras:
    products:
      - PH701
      - PHC701
      - NN4TV205PHGB
      - GTIP2PHWFGB
      - GTTV505MBGB
      - NNTV205MBGB
      - NNTV205PHGB
      - GTTV505PHGB
      - PHPEEPGB
  spy/our-full-range/spy-cameras/hidden-cameras:
    products:
      - GT4TV2SMKGB
      - GT4TV2PIRGB
      - GTIP2SMKWF
      - GTIP2PIRWF
      - GTIP2SMKHMWF
      - SPYPIR32WFGB
      - SPYPIR028WGB
      - SPYDCUPW
      - SPYDFOBW
      - SPYDUSBW
      - SPYDBATTW
      - SPYDHPW
  spy/our-full-range/spy-cameras/camera-recorders:
    products:
      - HCAME1B
      - SPYZ16
      - SPYZ18
      - SPYZ15
      - SPYZ32IR
      - SPYZ62WF
      - SPYDV90
      - HKIP205PH-LS
      - FSIP207PTZ
      - SPYDCUPW
      - SPYDFOBW
      - SPYDCAR
      - SPYDPKDVR1
      - SPYDALC
      - SPYDCAMBW
  spy/our-full-range/spy-cameras/systems:
    products:
      - TVIPH2G
      - 2PHEZ
      - DVRNNPH
      - DVRNNMB
  spy/our-full-range/wireless-cctv/portable-lcd-monitor:
    products:
      - 1DIGLAN1003
      - 1DIGLAN1005
      - 2DIGLAN1003
      - 4DIGLAN1003
      - 2DIGLAN1005
      - 4DIGLAN1005
      - DIGIRC1003
      - 1DIGLAN05SL
  spy/our-full-range/wireless-cctv/systems:
    products:
      - WL3ADIG24
      - 1DIGLAN1003
      - WLNVR1
      - WLIP230B
      - 1DIGLAN1005
      - 2DIGLAN1003
      - WLNVR4
      - PKE244WL
      - 4DIGLAN1003
      - TVI3T4WL
      - DW34QUALR
      - PKDIG204
      - 2DIGLAN1005
      - 4DIGLAN1005
      - PKWL74
      - PKDIG404
      - 2PHEZ
      - DW3E4B1TB1
      - PKDIG2EZ
      - PKIP4HKB
  spy/our-full-range/wireless-cctv/cameras:
    products:
      - 2DIG04IRC
      - DIGIRC1003
      - DIGIRC1005
      - DIGIR720HD
      - HKIP205DC-WA
      - DIGIRC1005SL
      - RSWLCAM
      - 1DIG04IRC
  spy/our-full-range/wireless-cctv/long-range-equipment:
    products:
      - 10DB24GHZANT
      - DIG24IR
      - COM5G2
      - DIG24PK
      - 7DB24GHZ
      - 7DB24GHZX4
      - 7DB24GHZX8
      - 7DB24GHZX2
      - DIG24PKWP
  spy/our-full-range/cctv-systems/coax-hd:
    products:
      - TVEZ32
      - TVIPH2G
      - TVEZ34
      - TVI7T4H
      - TVI6T4H
      - TVI6T8H
      - TVI7T8H
      - TV4K82
      - TV4K84
      - TV4K32
  spy/our-full-range/cctv-systems/network-ip:
    products:
      - PKE244
      - PKE274
      - PKE244WL
      - PKE484
      - PKE248
      - PKE278
      - PKIP34
      - PKIP74
      - PKIP38
      - PKIPANPR2
      - PKIP78
  spy/our-full-range/cctv-systems/4k-cctv:
    products:
      - PK4K32
      - PK4K74
      - PK4K34
  spy/our-full-range/cctv-systems/vehicle-security:
    products:
      - SPYZ16
      - SPYZ15
      - GNETGPS
      - SPYDCAR
      - VPIP82
  spy/our-full-range/cctv-cameras/coax-hd:
    products:
      - EZTV220BGB
      - HKTV220TC-L
      - HKTV240DGB
      - HKTV240BC-L
      - HKTV240BC-LZ
      - HKTV540TC-Z
      - HKTV540BC
      - HKTV540BC-Z
      - HKTV21015PTZ
      - HKTV520DC-V
      - HKTV220DC-LV
      - HKTV540DC-VZ
      - HKTV540TC
  spy/our-full-range/cctv-cameras/network-ip:
    products:
      - EZIP230B
      - EZIP230D
      - EZIP430D
      - EZIP430TMZ
      - HKIP830T-S
      - HKIP850B-S
      - HKIP830D-VS
      - HKIP430D-WFS
      - HKIP430D-VF
      - GTIP250PTZ
      - HKIP480B
      - HKIP210MD-AS
      - HKIP230LPR
      - HKIP230T-LS
      - HKIP230B-LS
      - HKIP430T-S
      - HKIP430B-S
      - HKIP450B-S
      - HKIP430D-VS
      - HKIP1215F-AS
      - HKIP21025PTZ
      - HKIP230D-LVS
      - HKIP21015PTZ
      - HKIP2120B-ZA
      - GTIP210PTZGB
      - HKIP20525PTZ
      - HKIP830B-S
      - EZIP420B
  spy/our-full-range/cctv-cameras/4k-cctv:
    products:
      - HKIP830T-S
      - HKIP850B-S
      - HKIP830D-VS
      - HKIP830B-S
  spy/our-full-range/cctv-cameras/thermal:
    products:
      - HKIR7B-B
      - HKIR10B
  spy/our-full-range/cctv-recorders/dvrs:
    products:
      - 4DVREZB
      - 4DVRRS2
      - 8DVREZC
      - 4DVRHK2D
      - 8DVRHK2D
      - 16DVRHK2C
      - 4DVRHK4
  spy/our-full-range/cctv-recorders/nvrs:
    products:
      - 4NVRHK2
      - 8NVRHK2
      - 16NVRHK24TB
      - 16NVRHK34TB
      - 4NVREZA
      - 8NVREZ1
  spy/our-full-range/cctv-recorders/4k-nvrs:
    products:
      - 16NVRHK34TB
  spy/our-full-range/wildlife-cameras/bird-box-cameras:
    products:
      - NC701G
      - NCIP9WF
      - NCIP220M
      - CMOSNC720M
      - NCF15EA20M
      - NCIP9WFBB
      - NC701GBB
      - CMOSNC720MBB
      - 2NCIP2
      - NCIP2
      - BB300
      - BBLED3
      - BB450
      - BBPLATE25
      - BBPLATE28
      - BBPLATE32
  spy/our-full-range/wildlife-cameras/outdoor-nature-cameras:
    products:
      - HCAME1B
      - WL3ADIG24
      - WLIP230B
      - HCAME1BOX
      - EZ4SD20B20M
  spy/our-full-range/wildlife-cameras/farm-kits:
    products:
      - WL3ADIG24
      - WLIP230B
      - WLPTZIP2B
      - WLPTZHKD
      - PKE244WL
      - TVI3T4WL
      - WLEZADIG24
      - DW34QUALR
      - DW3E4B1TB1
  spy/our-full-range/accessories/cables:
    products:
      - 5MRCA
      - 10MRCA
      - 20MRCA
      - 40MRCA
      - 50MRCA
      - 5M21POWER
      - 10M21POWER
      - 20M21POWER
      - 5M13POWER
      - 10M13POWER
      - 20M13POWER
      - VGACABLE
      - MAINSC13GB
      - 250RG59DCPRO
      - 10MBNCPRO
      - 20MBNCPRO
      - 30MBNCPRO
      - 40MBNCPRO
      - 50MBNCPRO
      - 60MBNCPRO
      - 100MRG59DC
      - 5M17POWER
      - 5MBNCPRO
      - 3MCAT5EG
      - 10MCAT5ODW
      - 20MCAT5ODW
      - 30MCAT5ODW
      - 100MCAT5EODB
      - 305MCAT5EODW
      - 40MCAT5ODW
      - 50MCAT5ODW
      - 5MCAT5ODW
      - 4BNC10MPRO
      - 4BNC20MPRO
      - 4BNC30MPRO
      - 8X100RG59TW
      - 8X250RG59TW
      - 5MBNCRCAPRO
      - 10MBNCRCAPRO
      - 20MBNCRCAPRO
      - 30MBNCRCAPRO
      - 40MBNCRCAPRO
      - 50MBNCRCAPRO
      - 60MBNCRCAPRO
      - AVCABLE
      - 2BNC10MPRO
      - 2BNC20MPRO
      - 2BNC30MPRO
  spy/our-full-range/accessories/networking:
    products:
      - PLINE21000
      - COM5G2
      - 5PORTPOEHK
      - 9PORTPOEHK
      - NGWFREP
      - UBNANO5G2
      - POEINJUB
      - ENSJBRA
      - PXT100M
      - VCPTX100MOD
      - VC4PORTMSW
      - ISPVIRGIN
      - ISPSKY
      - ISPTLKTLK
      - ISPVDFONE
  spy/our-full-range/accessories/power-supplies:
    products:
      - 12V10GB21
      - 12V20GB21
      - 12V10EU21
      - 12VCAR13
      - MAINSC13GB
      - BATT12V68GB
      - BATT8V68GB
      - 6V30GB17
      - BATTAA10
      - POEINJ
      - 8V05GB133M
      - POEINJUB
      - POEINJHK
      - 12V05GB21
  spy/our-full-range/accessories/connectors:
    products:
      - BNCTORCA
      - BNCTORCAX10
      - 21MMTO13MM
      - RCATOBNC
      - F2FPHONO
      - F2FPHONOX10
      - BNCTWIST
      - POWERJACKF
      - PWRJCKFX10
      - POWERJACKM
      - PWRJCKMX10
      - RCASCART
      - BNCTWISTX10
      - RG594PKTW
      - USB1PC
      - F2FBNC
      - BATTCLIP21
      - BAL201
      - RG594PKCR
      - RG591PKTW
      - RG591PKCR
      - POEINJSPL21
      - RJ45CON3U
      - RJ45CON3UX10
      - RJ45CON3UX20
      - IP66ENC
      - BATTCLIP13
      - RCATOHDMI
      - TVITOHDMI
      - BNCTPIECE-M
  spy/our-full-range/accessories/lenses:
    products:
      - LENS36MM
      - LENS6MM
  spy/our-full-range/accessories/data-storage:
    products:
      - SD8GB
      - MSD32GB
      - USB8GBSP
      - USB32GBSP
      - USB64GBSP
      - SD64GB
      - MSD64GB
      - MSD128GB
      - 1TBSSV
      - 2TBSSV
      - 4TBSSV
      - 6TBSSV
      - 8TBSSV
      - 10TBSSV
  spy/our-full-range/accessories/cctv-accessories:
    products:
      - QUAD01
      - CCTVSIGNA4
      - IDAUDIO
      - OSDUTCCON
      - LEDB50MGB
      - LEDB100M
      - PTZJOYIP05
      - IPAUDIO
      - IDAUDIOPRO
      - REC01
      - PTZJOYMINI
      - HK-BRA6
      - HKD-BRA1
      - HKD-BRA2
      - HK-BRA3
      - HKD-BRA4
      - HKD-BRA5
      - BRONZESETUP
      - SILVERSETUP
      - GOLDSETUP
      - PLATSETUP
      - FIREHOUSE
      - HKPTZBRA
      - GTB-BRA
      - GTD-BRA
      - 1DECHK
      - LEDMON28VV
      - LCDMON5GB
  spy/our-full-range/clearance/spy-cameras:
    products:
      - PH701R
      - SPYZ15R
      - SPYZ16R
      - SPYZ32IRR
      - SPYZ62WFR
      - SPYDV90R
      - PHC701R
  spy/our-full-range/clearance/cctv-cameras:
    products:
      - HKIP420BR
      - DIGIRC1003R
      - HKIP430BR
      - HKIP2100PTZR
      - ODDMVF516WR
      - ODPTZ62IRBR
      - HKIP830T-SR
      - HKIP430DWFR
  spy/our-full-range/clearance/cctv-recorders:
    products:
      - 4DVRRS2
  spy/our-full-range/clearance/wildlife-cameras:
    products:
      - HCAME1R
      - NC701GR
      - HCAME1BR
  spy/our-full-range/clearance/accessories:
    products:
      - 250RG59DCPRO
      - OSDUTCCON
      - BATT12V68GBR
      - 10M13POWERR
      - 10MRCAR
      - 20M13POWERR
      - 20MRCAR
      - DIG24PKWPR
